### ISSUE TITLE
[5] Misses make no sense

### ISSUE THREAD

**Issue by SKBotNL** [aflacc/ProjectFNF#109]
ProjectFNF version: 0.4-a
Type of issue: Mechanics
Severity: 5
Description: Sometimes it just says you missed when you didnt miss, it also happens on a certain note every single time

Video (on the green note it randomly says it is a miss):

https://user-images.githubusercontent.com/68018116/127851928-0a348794-e979-4564-bcc4-f226b9967fce.mp4

**Comment by MagnusStrom** [comment]
Thanks for the video! I'll look into this.

**Comment by MagnusStrom** [comment]
Fixed

**Comment by SKBotNL** [comment]
hmm, when I play the same song I still get the weird miss
(build from latest commit)
